controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

infinity:
    resource:
        path: '@InfinityBundle/src/Controller'
        namespace: Infinity\Controller
    type: attribute
    prefix: /admin
