controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

infinity:
    resource:
        path: '@InfinityBundle/Controller'
        namespace: InfinityBundle\Controller
    type: attribute
    prefix: /admin
